#!/bin/bash
## Scipt name : SHVpn
## Rasool.SF
## My E-Mail : safari@rasool.id.ir
## Version: 1.5-27.04.2017
username="Your-Username"
server="Your-Server-Address"
port="22" #your server ssh port
pidfile="/tmp/openconnect-pid"

if [ "$1" == "--config" ];then
    ssh-keygen
    ssh-copy-id -p "$port" "$username"@"$server"
fi

function connect()
{
    sudo sshuttle -r "$username"@"$server":"$port" 0.0.0.0/0 --daemon --pidfile="$pidfile"
    sleep 2
    echo "Connected to $server server!"
    echo "Your IP is"
    curl ifconfig.co
    exit
}

function disconnect()
{
    pid=`cat $pidfile`
	sudo kill -9 "$pid"
	sudo rm $pidfile
    echo "VPN Disconnected"
	echo "Yourt IP is: "
	curl ifconfig.co
	exit
}

if [ -f "$pidfile" ];then
	echo "VPN Status : Active"
	read -p "Mikhay SHVpn ro Disconnect konam ? (Y/N)" disconnect
	case "$disconnect" in
		"Y")
            disconnect
		;;
		"y")
			disconnect
		;;
		*)
			exit
	esac
else
	echo "VPN Status : Inactive"
	read -p "Mikhay SHVpn ro Connect konam ? (Y/N)" connected
	case "$connected" in
		"Y")
            connect
        ;;
		"y")
			connect
		;;
		*)
			exit
	esac
fi
